# Generated by Django 3.1 on 2020-08-20 04:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hurmused', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='musik',
            options={'ordering': ('-publish',)},
        ),
        migrations.AddField(
            model_name='musik',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='musik_posts', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='musik',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='musik',
            name='slug',
            field=models.SlugField(default=1, max_length=250, unique_for_date='publish'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='musik',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10),
        ),
    ]
