# Generated by Django 3.1 on 2020-08-20 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hurmused', '0002_auto_20200820_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='musik',
            name='author_sound',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
